//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioWeb.Auto.Net.servi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public System.Guid id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public System.DateTime Ano { get; set; }
        public Nullable<int> costo { get; set; }
        public string color { get; set; }
    }
}
